Create content for "Choosing a Laptop"
EssamWisam/cmp-docs pull request #20
Opened 2023-11-01 00:55 UTC by KnockerPulsar

closes #14

2023-11-01 00:56 UTC, KnockerPulsar commented
@EssamWisam would appreciate you assigning me on the issue as I can't seem to do so. 

Also, TODO: add some sort of generic minimum laptop specs section

2023-11-01 14:36 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +This type of laptop sacrifices performance and sometimes upgradability for the sake of being the most portable. You usually will have to pay more for similar specs to other types while receiving lowe
I would suggest that we use a more cautious language while presenting facts. So this could be made into 
> This type of laptop often sacrifices/may sacrifice performance and sometimes...
You can also mention a proof to further convince the reader, for instance `xyz` laptop has about similar specs to `abc` laptop while being about `140%` of the price in 2023.

2023-11-01 14:40 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +This type of laptop sacrifices performance and sometimes upgradability for the sake of being the most portable. You usually will have to pay more for similar specs to other types while receiving lowe
> Pick this if your commute is long and your back/shoulders are weak

Do you mean?

> Pick this if you don't want to break your back by buying a gaming laptop with a 1KG GPU and related stuff that you will almost never use.

Kidding of course, both are extreme but the point is you should expose this as a pro of this type of laptops (and not a con in whoever is buying it) since you are an unbiased liberal writer.

2023-11-01 14:48 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +This type of laptop sacrifices performance and sometimes upgradability for the sake of being the most portable. You usually will have to pay more for similar specs to other types while receiving lowe
> and you don't really care about performance.

WoW. You destroyed them here. I think liberal unbiased Tarek would rather write:

> and you are willing to raise the budget a little for decent performance.

2023-11-01 14:50 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Performance at the cost of everything else. These are heavy and hot, but they sure (usually) run fast. Be prepared to carry around a heavy power brick if you intend on doing more than one hour of wor
Again, a pros versus cons here would be really helpful. I find the heavy weight and extra bucks paid for the GPU, which most don't use to be a serious con, eh?

2023-11-01 14:52 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +The brains of the laptop. This will contribute greatly to how smooth and responsive your experience is with the laptop. These are usually called "Intel Core i7 9750H",  "AMD Ryzen 5 5500U", etc.. Let
A small introduction into what does it mean to have higher clock speed (more lines of code per second) and hence, faster startup, processing of items, etc. and likewise, for cores and any other main specs of the CPU you like.

2023-11-01 14:56 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Mainly contributes to how many applications you can run in parallel. Generally, the higher the ram capacity and frequency are, the better it is. So for example, an 8GB stick of ram is usually better
It would be nice to emphasize that this is among the most important specifications because an average dev. in our department has 100 chrome tabs open, 20 VSCode tabs open, a VM running in the background and sometimes Microsoft office. This is just an optional recommendation.

If you like, can also put true minimum bounds like that it's a terrible idea to go below 8GB and that it's highly recommended, for someone that wants to keep their laptop as is for long to go beyond 16GB. This would be hard to do for the processor, eh?

2023-11-01 14:58 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +### Screen
Maybe write below here that this is really an optional section for this that care about the display so someone doesn't feel overwhelmed that they have to read this.

2023-11-01 15:00 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Controls how much stuff you can download (pirate) from the internet. Storage drives have two types: NVMe SSDs and SATA HDDs (ignoring SATA SSDs since they aren't super popular for laptops.). The form
Could we estimate here what is a minimum storage size to be able to live with the large software we typically need to download in college? Along with a recommended storage size?

2023-11-01 15:01 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +### Storage Drives
I think you can divide this section into a beginner and advanced part (or similar) and beginner should only mention things like RAM, CPU and GPU; meanwhile, advanced goes into all the other stuff (chasis, inputs, etc.)

2023-11-01 15:06 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Mostly matters for gamers. For machine/deep learning aficionados, you'll probably use some cloud platform to train your models.
> Mostly matters for gamers. For machine/deep learning aficionados, you'll probably use some cloud platform to train your models. 

Crossed my mind that we can write:
> Mostly matters for gamers and those interested in artificial intelligence (machine learning and deep learning). The latter type of people usually have another preferred option such as training models on the cloud but some of them prefer using their own GPUs offline as it gives more flexibility.

2023-11-01 15:14 UTC, EssamWisam commented
Minor and optional comments. Marvelous work overall!

![image](https://github.com/EssamWisam/cmp-docs/assets/49572294/6d2d4beb-1cd3-4312-be95-c5e4edaf1704)

2023-11-11 22:57 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +This type of laptop sacrifices performance and sometimes upgradability for the sake of being the most portable. You usually will have to pay more for similar specs to other types while receiving lowe
> I would suggest that we use a more cautious language while presenting facts. So this could be made into
> 
> > This type of laptop often sacrifices/may sacrifice performance and sometimes...
> 
> You can also mention a proof to further convince the reader, for instance `xyz` laptop has about similar specs to `abc` laptop while being about `140%` of the price in 2023.

- I guess I was a bit too harsh on the thin and light crowd, will reword. 
- For the comparison of laptops, the prices fluctuate and depend on the shop you're buying from, so I suppose the best option would be letting the reader form their own opinion on the matter. 
- Pros and cons would probably be more concise, but lists are still broken so they look kinda ugly. Might be a good improvement for the future though!

2023-11-11 23:21 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +Performance at the cost of everything else. These are heavy and hot, but they sure (usually) run fast. Be prepared to carry around a heavy power brick if you intend on doing more than one hour of wor
Noted!

2023-11-11 23:22 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +The brains of the laptop. This will contribute greatly to how smooth and responsive your experience is with the laptop. These are usually called "Intel Core i7 9750H",  "AMD Ryzen 5 5500U", etc.. Let
Done! Didn't go really in depth as I wanted since its quite hard to boil down all the nuance.  Eagerly awaiting your feedback.

2023-11-11 23:31 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +Mainly contributes to how many applications you can run in parallel. Generally, the higher the ram capacity and frequency are, the better it is. So for example, an 8GB stick of ram is usually better
Good idea, but I doubt most first year students know VSCode or what a VM is, so perhaps it'd be a good idea to omit the details.

2023-11-11 23:34 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +### Screen
Perhaps it'd be a good idea to ask for feedback from first year students first? I don't want to accidentally make someone half blind because they bought a laptop with a bad screen :P

2023-11-11 23:42 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +Controls how much stuff you can download (pirate) from the internet. Storage drives have two types: NVMe SSDs and SATA HDDs (ignoring SATA SSDs since they aren't super popular for laptops.). The form
Good idea!

2023-11-11 23:43 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +### Storage Drives
Honestly, I don't think this is quite "advanced". It's more of "stuff that people don't care about until they do", so I think everyone should at least take a glance at everything.

2023-11-11 23:44 UTC, KnockerPulsar commented on public/department/General/Recently/Laptop.md
> +Mostly matters for gamers. For machine/deep learning aficionados, you'll probably use some cloud platform to train your models.
Hope you don't mind me "borrowing" this :)

2023-11-14 01:28 UTC, EssamWisam requested changes
Outstanding effort as I said earlier. Thank you so much for the valuable contribution, Tarek! Have highlighted a few minor things that could be improved. They are all optional!

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Set a budget range, filter out all laptops that don't fit your range or aren't in stock, filter out laptops that dont fit your usage, the watch as many reviews as you can for each laptop so you get t
```suggestion
Set a budget range, filter out all laptops that don't fit your range or aren't in stock, filter out laptops that dont fit your usage, then watch as many reviews as you can for each laptop so you get to know the pros and cons for each. You can then settle on one and buy it. Keep in mind that you can buy from Egypt for local warranty (for what it's worth), or from abroad if you want to save money.
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +The brains of the laptop. This will contribute greatly to how smooth and responsive your experience is with the laptop. These are usually called "Intel Core i7 9750H",  "AMD Ryzen 5 5500U", etc.. Let
```suggestion
The brains of the laptop. This will contribute greatly to how smooth and responsive your experience is with the laptop. These are usually called "Intel Core i7 9750H",  "AMD Ryzen 5 5500U", etc.. Let's begin by breaking down the naming convention:
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +#### Naming Convention
```suggestion

```
By removing this (the previous sentence has a colon anyway), you get rid of all of the following h5 titles (make them h4 instead) as h5 renders poorly in the website.

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +(Intel/AMD): These are the biggest two names in laptop processors at the time of writing (if we ignore apple for a minute), they're usually about equal, we'll discuss them a bit later on.
```suggestion
(Intel/AMD): These are the biggest two names in laptop processors at the time of writing (if we ignore Apple for a minute), they're usually about equal, we'll discuss them a bit later on. 
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +#### Resolution
```suggestion

#### Resolution
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Displays contents from the laptop. You'll be staring at this for hours every day. It's advised to at least aim for 1920x1080 for the resolution. You can live with lower resolutions, but they won't be
```suggestion
Displays contents from the laptop. You'll be staring at this for hours every day. It's advised to at least aim for 1920x1080 for the resolution. You can live with lower resolutions, but staring at them for a long time won't feel as good to your eyes.
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Controls how much stuff you can download (pirate) from the internet. Storage drives have two types: NVMe SSDs and SATA HDDs (ignoring SATA SSDs since they aren't super popular for laptops.). The form
```suggestion
Controls how much stuff you can download (pirate) from the internet. Storage drives have two types: NVMe SSDs and SATA HDDs (ignoring SATA SSDs since they aren't super popular for laptops.). The former is the faster, lighter, and (of course) more expensive option, while the latter allows you to get more storage capacity for cheaper. Some laptops come with only the former, some come only with the latter (cheaper ones), and some come with both. The author highly recommends at least an NVMe SSD for the OS (Windows or Linux). You can still live with a SATA HDD, but it will be SLOW (as in five minutes to boot slow vs 30 or less seconds on an NVMe SSD).
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +You can always expand your storage (check the spec sheet for available ports), or use an external drive. Most new laptops come with at least 256GB of NVMe storage or 1TB of HDD storage (or both). 256
```suggestion
You can always expand your storage (check the spec sheet for available ports), or use an external drive. Most new laptops come with at least 256GB of NVMe storage or 1TB of HDD storage (or both). 256GB should be the bare minimum you go with. At this size, you'll have to a lot more maintenance work like deleting temporary files and scanning for large files frequently. Also, forget doing any long-term storage (images, movies, games, course materials, etc... Higher capacities for the NVMe (512GB+) are strongly recommended.
```

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +### Storage Drives
Okay. Do you think we can reorder them around then? Thinking to promote Storage and GPU then speak about the rest (Screen, Ports, etc.) For the GPU, can remove "Optional" from the title and write it as a sentence.

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +### Screen
Fair enough. You know I highly value good screens. I was really referring to cooling, chasis, ports, inputs. These aren't high priority specs.

I agree anyway not to mention "advanced" or anything but just to order the specs by their importance (e.g., CPU, RAM, Storage, GPU, Screen, then the rest)

2023-11-14 01:28 UTC, EssamWisam commented on public/department/General/Recently/Laptop.md
> +Mainly contributes to how many applications you can run in parallel. Generally, the higher the ram capacity and frequency are, the better it is. So for example, an 8GB stick of ram is usually better
Can be easily swapped out for "code editor" and "virtual machine". I agree that it's not necessary to justify anyway. So you're good.

2024-01-11 18:33 UTC, EssamWisam commented
![image](https://github.com/EssamWisam/cmp-docs/assets/49572294/368b22a8-a0c4-4a65-af6a-69cb13713e3b)

2024-01-14 17:36 UTC, EssamWisam approved these changes

2024-01-14 19:10 UTC, merged