Arabic translation : About page
EssamWisam/cmp-docs pull request #3
Opened 2023-09-26 23:47 UTC by moste00

This PR is the first implementing Arabic translation. I chose the About page to translate first.

In addition, package.json was edited because export SET NODE_OPTIONS=--openssl-legacy-provider in the start script was giving errors on ubuntu 22.4 LTS. I hope it's not necessary on other OSes.

2023-09-27 07:49 UTC, EssamWisam requested changes

2023-09-27 07:49 UTC, EssamWisam commented on package.json
> +    "start": "react-scripts start",
This won't work on my machine. I think you only remove it if you are satisfying some Node.js version. It's surprising to me that the option  itself (which makes it work on my machine) breaks it for you because it should be a general solution. Could you let me know

- What error do you get when the option is set?
- What Node.js version do you have?

I think this can rather be a separate issue so I can merge the rest of the PR.

```suggestion
    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",
```

2023-09-27 07:50 UTC, EssamWisam commented
How beautiful. Thank you so much for this marvelous effort. It feels much better to see this Arabic page available.

2023-09-27 07:54 UTC, EssamWisam commented on public/department/Extras/About_ar.md
> +![image](https://i.imgur.com/f0Jqvs1.jpg)
I think a headline is missing
```suggestion
# 🧁 ايه هي CMP Docs
![image](https://i.imgur.com/f0Jqvs1.jpg)
```

2023-09-27 17:21 UTC, moste00 commented on package.json
> +    "start": "react-scripts start",
Hmmm. That's why I hate Node. 

My version of node is v12.22.9. My version of npm is 8.5.1. Running without the export just works, adding it back gives me : 

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

2023-09-27 17:24 UTC, moste00 commented on package.json
> +    "start": "react-scripts start",
The easiest possible fix I can imagine is for you to reject this change, keeping the --openssl version as the canonical one. And adding contributor advice about it so that ubuntu devs don't get burned by it. I can remove this file from the commit and force-push the branch and the PR would update automatically.

Anything other than that would be a deep dive into whatever dependency you have that requires this openssl option. Maybe try Deno. I'm only half-joking.

2023-09-27 17:27 UTC, moste00 commented on public/department/Extras/About_ar.md
> +![image](https://i.imgur.com/f0Jqvs1.jpg)
It probably will, RTL is very easy to break. At least in VS code. Let's just push the change and we can always fix it later.

2023-10-08 13:44 UTC, EssamWisam commented on public/department/Extras/About_ar.md
> +![image](https://i.imgur.com/f0Jqvs1.jpg)
> It probably will, RTL is very easy to break.
@moste00 Thanks, that gave me tons of encouragement to merge when I saw this xD. I just tested it now and it did not break.

Next time please sync your fork with the most recent dev so that your work can be seen when netlify deploys a view of your PR.

2023-10-08 13:46 UTC, EssamWisam commented on package.json
> +    "start": "react-scripts start",
> The easiest possible fix I can imagine is for you to reject this change, keeping the --openssl version as the canonical one. 
Yes, dear. You could have equivalently committed my suggestion.
> And adding contributor advice about it so that ubuntu devs don't get burned by it.
My gut feelings suggest that this is about the Node version but will look into it anyway.

2023-10-08 13:48 UTC, merged